### ISSUE TITLE
os not defined in settings.py

### ISSUE THREAD

**Issue by sevenearths** [mjstealey/django-startproject-docker#14]
```
# docker run --rm \
  -e PROJECT_NAME=genesys_call_recording \
  -v $(pwd):/code \
  mjstealey/django-startproject-docker \
  --nginx \
  --ssl-certs \
  --owner-uid $(id -u) \
  --owner-gid $(id -g)
### Generate with Nginx ###
### Generate with SSL self-signed Certificates ###
### Set owner UID = 1004 ###
### Set owner UID = 1005 ###
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/ef/53/1f609efbd75f7ffc8f9ca94e4fbf971b38a4c15e3a18fd9db5c499cb68b8/virtualenv-20.0.34-py2.py3-none-any.whl (4.9MB)
Collecting appdirs<2,>=1.4.3 (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Collecting importlib-metadata<3,>=0.12; python_version < "3.8" (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/6d/6d/f4bb28424bc677bce1210bc19f69a43efe823e294325606ead595211f93e/importlib_metadata-2.0.0-py2.py3-none-any.whl
Collecting six<2,>=1.9.0 (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting filelock<4,>=3.0.0 (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
Collecting distlib<1,>=0.3.1 (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/f5/0a/490fa011d699bb5a5f3a0cf57de82237f52a6db9d40f33c53b2736c9a1f9/distlib-0.3.1-py2.py3-none-any.whl (335kB)
Collecting zipp>=0.5 (from importlib-metadata<3,>=0.12; python_version < "3.8"->virtualenv)
  Downloading https://files.pythonhosted.org/packages/15/1b/dbf5af0148ba527fb2164d2a2ecf623e77ca93877a83379a5b1aab563e40/zipp-3.3.0-py3-none-any.whl
Installing collected packages: appdirs, zipp, importlib-metadata, six, filelock, distlib, virtualenv
Successfully installed appdirs-1.4.4 distlib-0.3.1 filelock-3.0.12 importlib-metadata-2.0.0 six-1.15.0 virtualenv-20.0.34 zipp-3.3.0
WARNING: You are using pip version 19.1.1, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
created virtual environment CPython3.7.3.final.0-64 in 464ms
  creator CPython3Posix(dest=/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==20.2.3, setuptools==50.3.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Requirement already up-to-date: pip in /venv/lib/python3.7/site-packages (20.2.3)
Collecting Django
  Downloading Django-3.1.2-py3-none-any.whl (7.8 MB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.8.6-cp37-cp37m-manylinux1_x86_64.whl (3.0 MB)
Collecting pytest
  Downloading pytest-6.1.1-py3-none-any.whl (272 kB)
Collecting pytest-cov
  Downloading pytest_cov-2.10.1-py2.py3-none-any.whl (19 kB)
Collecting pytest-django
  Downloading pytest_django-3.10.0-py2.py3-none-any.whl (19 kB)
Collecting python-dotenv
  Downloading python_dotenv-0.14.0-py2.py3-none-any.whl (17 kB)
Collecting uWSGI
  Downloading uWSGI-2.0.19.1.tar.gz (803 kB)
Collecting asgiref~=3.2.10
  Downloading asgiref-3.2.10-py3-none-any.whl (19 kB)
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
Collecting pytz
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting py>=1.8.2
  Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Using cached importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting attrs>=17.4.0
  Downloading attrs-20.2.0-py2.py3-none-any.whl (48 kB)
Collecting iniconfig
  Downloading iniconfig-1.0.1-py3-none-any.whl (4.2 kB)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting toml
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting coverage>=4.4
  Downloading coverage-5.3-cp37-cp37m-manylinux1_x86_64.whl (229 kB)
Collecting zipp>=0.5
  Using cached zipp-3.3.0-py3-none-any.whl (5.3 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Building wheels for collected packages: uWSGI
  Building wheel for uWSGI (setup.py): started
  Building wheel for uWSGI (setup.py): finished with status 'done'
  Created wheel for uWSGI: filename=uWSGI-2.0.19.1-cp37-cp37m-linux_x86_64.whl size=595625 sha256=9a84c85ac598dbd4169fbdc310701e32ba9698f4592e89fd87697e66e5988d35
  Stored in directory: /root/.cache/pip/wheels/0c/f9/df/fb7fb12204a8f5c67682f31e10485863c24123a2a626e71203
Successfully built uWSGI
Installing collected packages: asgiref, sqlparse, pytz, Django, psycopg2-binary, py, zipp, importlib-metadata, attrs, iniconfig, pluggy, toml, six, pyparsing, packaging, pytest, coverage, pytest-cov, pytest-django, python-dotenv, uWSGI
Successfully installed Django-3.1.2 asgiref-3.2.10 attrs-20.2.0 coverage-5.3 importlib-metadata-2.0.0 iniconfig-1.0.1 packaging-20.4 pluggy-0.13.1 psycopg2-binary-2.8.6 py-1.9.0 pyparsing-2.4.7 pytest-6.1.1 pytest-cov-2.10.1 pytest-django-3.10.0 python-dotenv-0.14.0 pytz-2020.1 six-1.15.0 sqlparse-0.4.1 toml-0.10.1 uWSGI-2.0.19.1 zipp-3.3.0
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/genesys_call_recording/genesys_call_recording/settings.py", line 24, in <module>
    DEBUG = os.getenv('DEBUG', True)
NameError: name 'os' is not defined
# 
```

**Comment by SaddamHusseinsCorgi** [comment]
Getting the same problem unfortunately.

**Comment by kruglovks** [comment]
The same problem as well
